name: Create Artifact URLs

on:
  workflow_run:
    workflows: ["Upload Artifact"]
    types: [completed]

jobs:
  job-two:
    runs-on: ubuntu-latest
    steps:
      - run: |
          ART_ID = $(curl -H "Accept: application/vnd.github+json" \
          ${{ github.event.workflow_run.artifacts_url }} |
          jq .artifacts[].id)
          
          echo "https://github.com/${{ github.repository }}/suites/${{ github.event.workflow_run.check_suite_id }}/artifacts/$ART_ID"
