name: Create Artifact URLs

on:
  workflow_run:
    workflows: ["Upload Artifact"]
    types: [completed]

jobs:
  job-two:
    runs-on: ubuntu-latest
    steps:
      - run: |
          curl -H "Accept: application/vnd.github+json" \
          ${{ github.event.workflow_run.artifacts_url }} |
          jq .artifacts[].id
